const styles = {
        qtyButton: {
        padding: '0.25rem 0.75rem',
        backgroundColor: '#EEE',
        border: '1px solid #CCC',
        borderRadius: '4px',
        fontSize: '1rem',
        cursor: 'pointer',
        fontWeight: 'bold',
        },
        quantityControl:{
            padding: '15px',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            gap: '10px'},
        list: {
            display: 'flex',
            flexWrap: 'wrap',
            gap: '1rem',
            justifyContent: 'center',
        },
        addToCart:{
            marginTop: '0.8rem',
            padding: '0.5rem 1rem',
            backgroundColor: '#E53935',
            color: '#fff',
            border: 'none',
            borderRadius: '4px',
            cursor: 'pointer',
            fontWeight: 'bold',
            width: '100%',
            },
        card: {
            border: '1px solid #ddd',
            borderRadius: '8px',
            width: 280,
            padding: '1rem',
            boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
            fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
            backgroundColor: '#fff',
        },
        image: {
            width: '100%',
            height: 160,
            borderRadius: '4px',
            objectFit: 'contain',
            marginBottom: '0.8rem',
        },
        title: {
            fontSize: '1.1rem',
            margin: '0 0 0.4rem 0',
            height: 48,
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            display: '-webkit-box',
            WebkitLineClamp: 2,
            WebkitBoxOrient: 'vertical',
        },
        brandModel: {
            color: '#555',
            fontSize: '0.85rem',
            margin: '0 0 0.2rem 0',
        },
        category: {
            fontSize: '0.8rem',
            color: '#888',
            margin: '0 0 0.6rem 0',
        },
        description: {
            fontSize: '0.85rem',
            color: '#444',
            margin: '0 0 0.8rem 0',
            height: 55,
            overflow: 'hidden',
            textOverflow: 'ellipsis',
            display: '-webkit-box',
            WebkitLineClamp: 3,
            WebkitBoxOrient: 'vertical',
        },
        priceWrapper: {
            display: 'flex',
            alignItems: 'center',
            gap: '0.6rem',
        },
        originalPrice: {
            textDecoration: 'line-through',
            color: '#999',
            fontSize: '0.9rem',
        },
        price: {
            fontWeight: 'bold',
            color: '#E53935',
            fontSize: '1.1rem',
        },
        discount: {
            color: '#4CAF50',
            fontWeight: '600',
            fontSize: '0.9rem',
        },
    };
    export default styles;